//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SetId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int StorageId { get; set; }
        public int ProductTypeId { get; set; }
        public double Amount { get; set; }
        public int UnitTypeId { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Set Set { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
